#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

SYSTEMDDIR="/root/writable/system-data/etc/systemd"
JOBDIR="${SYSTEMDDIR}/system"
SERVICENAME="serial-getty@ttyGS0.service"

[ -e "/root/writable/system-data/etc/modules-load.d/gserial.conf" ] || \
       echo "g_serial" >/root/writable/system-data/etc/modules-load.d/gserial.conf

if [ ! -L "${JOBDIR}/getty.target.wants/${SERVICENAME}" ]; then
       cp /root/lib/systemd/system/serial-getty@.service ${JOBDIR}/${SERVICENAME}
       ln -s /etc/systemd/system/${SERVICENAME} ${JOBDIR}/getty.target.wants/${SERVICENAME}
fi
