#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

SYSTEMDDIR="/root/writable/system-data/etc/systemd"
JOBDIR="${SYSTEMDDIR}/system"
SERVICENAME="getty@ttyGS0.service"

[ -e "/root/writable/system-data/etc/modules-load.d/gserial.conf" ]  || \
	echo "g_serial" >/root/writable/system-data/etc/modules-load.d/gserial.conf

[ -L "${JOBDIR}/getty.target.wants/${SERVICENAME}" ] || \
	ln -s "/lib/systemd/system/getty@.service" "${JOBDIR}/getty.target.wants/${SERVICENAME}"
