#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

/sbin/modprobe -v libcomposite
/sbin/modprobe -v u_serial
/sbin/modprobe -v usb_f_acm
/sbin/modprobe -v g_serial
