name: orangepi-zero-ogra
version: 16-0.1
summary: Orange Pi Zero
description: |
 Bootloader files and partitoning data to create a
 bootable Ubuntu Core image for the Orange Pi Zero.
type: gadget

architectures:
  - build-on: amd64
    run-on: armhf

confinement: strict
grade: stable

parts:
  uboot:
    plugin: nil
    source: git://git.denx.de/u-boot.git
    source-branch: v2018.05
    override-build: |
      git apply ../../../uboot.patch
      TCHAINVER="$(wget -q -O - \
                 https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/| \
                 html2text -width 200|grep 'x86_64_arm-linux-gnueabihf.tar.xz '|cut -d' ' -f2)"
      wget https://releases.linaro.org/components/toolchain/binaries/latest-7/arm-linux-gnueabihf/$TCHAINVER
      tar xf $TCHAINVER
      mv $(echo $TCHAINVER|sed 's/.tar.xz$//') toolchain
      CROSS_COMPILE=$(pwd)/toolchain/bin/arm-linux-gnueabihf- make orangepi_zero_defconfig
      CROSS_COMPILE=$(pwd)/toolchain/bin/arm-linux-gnueabihf- make
      cp u-boot-sunxi-with-spl.bin $SNAPCRAFT_PART_INSTALL/
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      cd $SNAPCRAFT_PART_INSTALL/; ln -s uboot.env uboot.conf
    build-packages:
      - libpython2.7-dev
      - build-essential
      - bc
      - bison
      - device-tree-compiler
      - flex
      - html2text
      - python-minimal
      - swig
      - wget
  initrd-snippet:
    source: .
    plugin: nil
    override-build: |
      set -e
      cd initrd && find . | cpio --quiet -o -H newc| lzma >>$SNAPCRAFT_PART_INSTALL/initrd-extra.img
    build-packages:
      - cpio
      - findutils
      - xz-utils
      - gcc-arm-linux-gnueabihf

slots:
  i2c-0:
    interface: i2c
    path: /dev/i2c-0
  i2c-1:
    interface: i2c
    path: /dev/i2c-1
  i2c-2:
    interface: i2c
    path: /dev/i2c-2
  opi-gpio-0:
    interface: gpio
    number: 0
  opi-gpio-1:
    interface: gpio
    number: 1
  opi-gpio-10:
    interface: gpio
    number: 10
  opi-gpio-11:
    interface: gpio
    number: 11
  opi-gpio-12:
    interface: gpio
    number: 12
  opi-gpio-13:
    interface: gpio
    number: 13
  opi-gpio-14:
    interface: gpio
    number: 14
  opi-gpio-15:
    interface: gpio
    number: 15
  opi-gpio-16:
    interface: gpio
    number: 16
  opi-gpio-18:
    interface: gpio
    number: 18
  opi-gpio-19:
    interface: gpio
    number: 19
  opi-gpio-198:
    interface: gpio
    number: 198
  opi-gpio-199:
    interface: gpio
    number: 199
  opi-gpio-2:
    interface: gpio
    number: 2
  opi-gpio-3:
    interface: gpio
    number: 3
  opi-gpio-6:
    interface: gpio
    number: 6
  opi-gpio-7:
    interface: gpio
    number: 7
  serial-1:
    interface: serial-port
    path: /dev/ttyS1
  serial-2:
    interface: serial-port
    path: /dev/ttyS2
